### ISSUE TITLE
I need to add some data to this application- update to some of the data

### ISSUE THREAD

**Issue by wetlandsDiane** [UGS-GIO/wetlands#26]
**-Provide the basic identification information for each dataset (e.g., title, description, source, point of contact).**
-Title: Landscape Data
-Description: I have updated data for the surface water extent fields in the HUC12 and HUC layers, as well as updated plots. Other spatial scales will not have the surface water extent data
-Source: Calculations done by Rebecca Lee using the Global Surface Water Mapper data in Google Earth Engine
-Point of Contact: Diane Menuz
-File/folder location of data: M:\Shared drives\UGS_Wetlands\Projects\LandscapeData\surfaceWaterExtent

**What is the purpose/intent of each dataset in context to the project?**
To provide information on trends in surface water across Utah over the last 30 years

Is this grant-funded? If yes, what is the billing code?
Either UW19 or UW20, depending on how many hours you have left to be billed on each of these grants

**What do you want the popups for each dataset to look like?**
-Martha will reach out to you with a sheet for you to fill out.

**Once you submit this issue, your data will be reviewed and checked off by the following people (using Github):**
-Product Manager
-Data Manager
-Technical Reviewer (only the text within the database/app: if it's in full sentence format)
-Web Services Manager

**Data Management staff will reach out to you within the next couple of days to give an estimate of how long it will take to add your new data.

**Comment by marthajensen** [comment]
@jjhi11  The HUC 8 and HUC 12 layers have been fully updated with new data. All surface water fields have been updated. 


**surface_water_plot** field now has full URL's to plots located on the Server

Two domains have also been added so that you can use the short integer value of the field to stylize the data.

The **surface_water_lag** domain is:

![image](https://user-images.githubusercontent.com/11522897/135308676-b9719a30-5061-4af7-a7a7-25c1463101b7.png)


The **surface_water_trend** domain is:

![image](https://user-images.githubusercontent.com/11522897/135308755-7298e0de-b32f-4cfd-b4b0-e44cec485037.png)
